project_id = "feufqhnajidhqkxxddfc"

[functions.ai-biography]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.ai-pin-verify]
verify_jwt = false

[functions.ai-receipt]
verify_jwt = false

[functions.ai-test]
verify_jwt = false

[functions.ai-whisper]
verify_jwt = false
